ingest_data_task:
  func: py-sync-fs-triples
  args:
    root: /data
    read_uri: http://graphdb:7201/repositories/kgap
    write_uri: http://graphdb:7201/repositories/kgap/statements

travharv_task:
  func: py-trav-harv
  args:
    config: /data/travharv_config/
    target_store_info:
      - http://graphdb:7201/repositories/kgap
      - http://graphdb:7201/repositories/kgap/statements

rdf_production_task:
  func: pysubyt
  args:
    input: /data/pubs_sdg_info.csv
    output: /data/pubs_sdg_info.ttl
    template:
      jinja_root: templates
      file_name: sdg.ldt.j2
    mode: no-iteration
    force: true