PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/#>

SELECT DISTINCT 
    ?collection 
    ?title 
    ?publication

WHERE { 
	?collection a <https://schema.org/Collection> .
    ?collection <http://purl.org/dc/terms/#title> ?title .
    ?collection <http://www.w3.org/ns/dcat#resource> ?publication .
	?publication a dct:BibliographicResource .     
}